name: Android CI

on:
  push:
    branches:  
    - develop-mHBS 
    - master
    - bhavesh3005sharma-patch-1
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Loading Submodules
      run: git submodule update –init –recursive
    - name: Grant execute permission for ./gradlew
      run: chmod +x gradlew
    - name: Build Dhis Application
      run: ./gradlew assembleDhisDebug
    - name: Upload Apk Artifact

      uses: actions/upload-artifact@v2
      with:
        name: dhis-debug-application
        path: ./app/build/outputs/apk/dhis/debug/app-dhis-debug.apk
